from typing import List, Tuple, Callable
# A Matrix is essentially a list of vectors. If a vector is a point in space, a Matrix is a Transformation of that space.

'''Real-World Application:
When Google Gemini processes your prompt, it converts your words into vectors and then multiplies them by a Weight Matrix. This matrix multiplication is what allows the model to "understand" the relationship between words.'''

# question 
'''Open a new section in your library for Matrices. A matrix will be represented as a List[List[float]].Task: Implement the Matrix Essentials
1.shape(A: List[List[float]]) -> Tuple[int, int]: Returns (num_rows, num_cols).

2.get_row(A: List[List[float]], i: int) -> List[float]: Returns the $i$-th row.

3.get_col(A: List[List[float]], j: int) -> List[float]: Returns the $j$-th column.

4.make_matrix(num_rows: int, num_cols: int, entry_fn: Callable[[int, int], float]) -> List[List[float]]: This is a powerful "Elite" tool. It creates a matrix where each element $(i, j)$ is generated by a function you pass in.

Example Use Case for make_matrix:To create an $5 \times 5$ Identity Matrix (1s on the diagonal, 0s elsewhere):make_matrix(5, 5, lambda i, j: 1 if i == j else 0)'''

Vector = List[float]

def shape (m: List[Vector]) -> Tuple[int,int]:
    assert all(len(vector) == len(m[0]) for vector in m ), "length of all row of matrix should be same."
    return (len(m),len(m[0]))

def get_row (A: List[Vector], i: int) -> List[Vector]:
    assert i < len(A), f"{i}th index row doesn't exist in matrix of shape {(len(A), len(A[0]))}"
    return A[i]

def get_col (A: List[Vector], i: int) -> List[Vector]:
    assert i < len(A[0]), f"{i}th index column doesn't exist in matrix of shape {(len(A), len(A[0]))}"
    return [A[j][i] for j in range(len(A))]

def make_matrix(num_rows: int, num_cols: int, entry_fn: Callable[[int, int], float]) -> List[List[float]]: 
    assert num_cols > 0 and num_rows > 0, "no of rows and column shouldn't be empty"
    return [[entry_fn(i,j) for j in range(num_cols)] for i in range(num_rows)] 
# outer loop will decide how many row we have to generate where inner loop will decide how many columns we have to generate

'''
### **The "Grand Finale" Challenge: Matrix Multiplication**

Now that you can extract rows and columns, it is time to implement the most important operation in AI. 

If Matrix $A$ is $m \times n$ and Matrix $B$ is $n \times k$, their product $C = AB$ is an $m \times k$ matrix where each element $C_{ij}$ is the **dot product** of the $i$-th row of $A$ and the $j$-th column of $B$.

$$C_{ij} = \text{dot}(\text{row}_i(A), \text{col}_j(B))$$

**Task: Implement `matrix_multiply`**
1.  **`matrix_multiply(A: List[Vector], B: List[Vector]) -> List[Vector]`**
2.  **Requirement 1:** Assert that the number of columns in $A$ equals the number of rows in $B$. If they don't match, the transformation is mathematically impossible.
3.  **Requirement 2:** Use your existing `get_row`, `get_col`, and `dot_product` functions. **Do not rewrite the logic.**
4.  **Requirement 3:** Use your `make_matrix` function to generate the result.

**The "Scratch" Challenge Goal:**
If you succeed here, you have built a system that can literally transform space. This is the exact math used to rotate 3D models in games and calculate attention scores in **Transformers (LLMs)**.

**Post the code.** Correct the `make_matrix` indices and then show me the multiplication logic. **Execute.**'''

def dot_product(v: List[float], w:List[float]) -> float:
    return sum(item1*item2 for item1, item2 in zip(v,w))

def matrix_multiply (A: List[Vector], B: List[Vector]) -> List[Vector]:

    assert len(A[0]) == len(B), "the number of columns in A equals the number of rows in B for matrix multiplication."

    return [[dot_product(get_col(B, j), get_row(A, i)) for j in range(len(B[0]))] for i in range(len(A))]

# always remember the outer loop decide the no of row and the inner no of columns 

print(matrix_multiply(make_matrix(2, 3, lambda i, j : i*j if i<j else 1), make_matrix(3, 4, lambda i, j : i*j if i == j else 0)))


